version: '3'

services:
  db:
    image: postgres:14.3-alpine
    volumes:
      - newspaper_db:/var/lib/postgresql/data/
    hostname: db
    environment:
      - POSTGRES_NAME=newspaper_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nikita123
    networks:
      some_network:
  web:
    build: .
    command: python /usr/src/newspaper/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/newspaper
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=newspaper_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nikita123
    env_file:
      - ./.env.dev
    depends_on:
      - db
    links:
      - db:db
    networks:
      some_network:

networks:
 some_network:

volumes:
  newspaper_db:
