version: '3'

services:
  web:
    build: ./web
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/web_app
    ports:
      - '8000:8000'
    environment:
      - POSTGRES_NAME=newspaper_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nikita123
    depends_on:
      - db
    env_file:
      - .env.dev
  db:
    image: postgres:14.3-alpine
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nikita123
      - POSTGRES_DB=newspaper_db