type = "ClassType"
name = "Car"
[[bases]]
type = "ClassType"
name = "object"

[type_definition.__init__]
type = "FunctionType"

[type_definition.__eq__]
type = "FunctionType"

[type_definition.get_info]
type = "FunctionType"

[type_definition.ride]
type = "FunctionType"

[type_definition.__init__.__globals__]

[type_definition.__init__.__code__]
type = "CodeType"
co_nlocals = 9
co_name = "__init__"
co_argcount = 9
co_varnames = [ "self", "color", "weight", "fuel_consumption", "year_of_release", "price", "name", "model", "engine",]
co_names = [ "_Car__color", "_Car__weight", "_Car__fuel_consumption", "_Car__year_of_release", "_Car__price", "_Car__name", "_Car__model", "_Car__engine",]
co_cellvars = []
co_freevars = []
co_posonlyargcount = 0
co_kwonlyargcount = 0
co_firstlineno = 21
co_lnotab = [ 0, 9, 6, 1, 6, 1, 6, 1, 6, 1, 6, 1, 6, 1, 6, 1,]
co_stacksize = 2
co_code = [ 124, 1, 124, 0, 95, 0, 124, 2, 124, 0, 95, 1, 124, 3, 124, 0, 95, 2, 124, 4, 124, 0, 95, 3, 124, 5, 124, 0, 95, 4, 124, 6, 124, 0, 95, 5, 124, 7, 124, 0, 95, 6, 124, 8, 124, 0, 95, 7, 100, 0, 83, 0,]
co_consts = [ "None",]
co_flags = 67

[type_definition.__eq__.__globals__]

[type_definition.__eq__.__code__]
type = "CodeType"
co_nlocals = 2
co_name = "__eq__"
co_argcount = 2
co_varnames = [ "self", "other",]
co_names = [ "_Car__color", "_Car__weight", "_Car__fuel_consumption", "_Car__year_of_release", "_Car__price", "_Car__name", "_Car__model", "_Car__engine",]
co_cellvars = []
co_freevars = []
co_posonlyargcount = 0
co_kwonlyargcount = 0
co_firstlineno = 39
co_lnotab = [ 0, 1, 12, 1, 10, 255, 2, 2, 10, 254, 2, 3, 10, 253, 2, 4, 10, 252, 2, 5, 10, 251, 2, 6, 10, 250, 2, 7, 10, 249, 2, 8, 4, 2,]
co_stacksize = 2
co_code = [ 124, 0, 106, 0, 124, 1, 106, 0, 107, 2, 114, 50, 124, 0, 106, 1, 124, 1, 106, 1, 107, 2, 114, 50, 124, 0, 106, 2, 124, 1, 106, 2, 107, 2, 114, 50, 124, 0, 106, 3, 124, 1, 106, 3, 107, 2, 114, 50, 124, 0, 106, 4, 124, 1, 106, 4, 107, 2, 114, 50, 124, 0, 106, 5, 124, 1, 106, 5, 107, 2, 114, 50, 124, 0, 106, 6, 124, 1, 106, 6, 107, 2, 114, 50, 124, 0, 106, 7, 124, 1, 106, 7, 107, 2, 114, 50, 100, 1, 83, 0, 100, 2, 83, 0,]
co_consts = [ "None", true, false,]
co_flags = 67

[type_definition.get_info.__globals__]
get_info = "recursive"

[type_definition.get_info.__code__]
type = "CodeType"
co_nlocals = 1
co_name = "get_info"
co_argcount = 1
co_varnames = [ "self",]
co_names = [ "print", "_Car__color", "_Car__weight", "_Car__fuel_consumption", "_Car__price", "_Car__name", "_Car__model", "_Car__engine", "get_info",]
co_cellvars = []
co_freevars = []
co_posonlyargcount = 0
co_kwonlyargcount = 0
co_firstlineno = 52
co_lnotab = [ 0, 1, 16, 1, 16, 1, 16, 1, 16, 1, 16, 1, 16, 1,]
co_stacksize = 3
co_code = [ 116, 0, 100, 1, 124, 0, 106, 1, 155, 0, 157, 2, 131, 1, 1, 0, 116, 0, 100, 2, 124, 0, 106, 2, 155, 0, 157, 2, 131, 1, 1, 0, 116, 0, 100, 3, 124, 0, 106, 3, 155, 0, 157, 2, 131, 1, 1, 0, 116, 0, 100, 4, 124, 0, 106, 4, 155, 0, 157, 2, 131, 1, 1, 0, 116, 0, 100, 5, 124, 0, 106, 5, 155, 0, 157, 2, 131, 1, 1, 0, 116, 0, 100, 6, 124, 0, 106, 6, 155, 0, 157, 2, 131, 1, 1, 0, 124, 0, 106, 7, 160, 8, 161, 0, 1, 0, 100, 0, 83, 0,]
co_consts = [ "None", "Color: ", "Weight: ", "Fuel consumption: ", "Price: ", "Name: ", "Model: ",]
co_flags = 67

[type_definition.ride.__globals__]

[type_definition.ride.__code__]
type = "CodeType"
co_nlocals = 1
co_name = "ride"
co_argcount = 1
co_varnames = [ "self",]
co_names = [ "print", "_Car__name", "_Car__model",]
co_cellvars = []
co_freevars = []
co_posonlyargcount = 0
co_kwonlyargcount = 0
co_firstlineno = 61
co_lnotab = [ 0, 1,]
co_stacksize = 5
co_code = [ 116, 0, 124, 0, 106, 1, 155, 0, 100, 1, 124, 0, 106, 2, 155, 0, 100, 2, 157, 4, 131, 1, 1, 0, 100, 0, 83, 0,]
co_consts = [ "None", " ", " is riding now!",]
co_flags = 67
